spring:
  application:
    name: "login"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/nome_do_banco
    username: usuario
    password: senha